# Generated by Django 6.1.1 on 2026-09-25 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_mobile_userprofile_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='resend_count',
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='last_otp_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
