# Generated by Django 6.1.1 on 2026-09-30 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_space', '0004_hashtag_alter_friendrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mention',
            unique_together={('post', 'user')},
        ),
        migrations.RemoveField(
            model_name='mention',
            name='mentioned_by',
        ),
        migrations.RemoveField(
            model_name='mention',
            name='mentioned_user',
        ),
    ]
