# Generated by Django 6.1.1 on 2026-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_internshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='quota_reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='quota_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
