# Generated by Django 6.1.1 on 2026-09-17 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='resume_photos/')),
                ('career_objective', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('internships', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('social_links', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('template', models.CharField(default='template1', max_length=50)),
                ('font', models.CharField(default='Arial', max_length=50)),
                ('color', models.CharField(default='black', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
